# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1239, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.TotalPage = QtWidgets.QFrame(self.centralwidget)
        self.TotalPage.setStyleSheet("QFrame{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"}")
        self.TotalPage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TotalPage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TotalPage.setObjectName("TotalPage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.TotalPage)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.NavigatePart = QtWidgets.QFrame(self.TotalPage)
        self.NavigatePart.setStyleSheet("QFrame#NavigatePart{\n"
"    background-color: qlineargradient(x0:0, y0:1, x2:0, y2:1,stop:0 rgb(97, 150, 255), stop:1 rgb(68, 114, 196));\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-bottom-left-radius:10px;\n"
"}")
        self.NavigatePart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NavigatePart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NavigatePart.setObjectName("NavigatePart")
        self.formLayout = QtWidgets.QFormLayout(self.NavigatePart)
        self.formLayout.setObjectName("formLayout")
        self.PageButtonGroup = QtWidgets.QFrame(self.NavigatePart)
        self.PageButtonGroup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PageButtonGroup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PageButtonGroup.setObjectName("PageButtonGroup")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.PageButtonGroup)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PageCloseButton = QtWidgets.QPushButton(self.PageButtonGroup)
        self.PageCloseButton.setMinimumSize(QtCore.QSize(12, 12))
        self.PageCloseButton.setMaximumSize(QtCore.QSize(12, 12))
        self.PageCloseButton.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(240, 108, 96);\n"
"border:1px solid rgba(113, 17, 15,50);\n"
"border-radius:6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(139, 29, 31)\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 59, 35);\n"
"}\n"
"")
        self.PageCloseButton.setText("")
        self.PageCloseButton.setObjectName("PageCloseButton")
        self.horizontalLayout.addWidget(self.PageCloseButton)
        self.PageMinimizeButton = QtWidgets.QPushButton(self.PageButtonGroup)
        self.PageMinimizeButton.setMinimumSize(QtCore.QSize(12, 12))
        self.PageMinimizeButton.setMaximumSize(QtCore.QSize(12, 12))
        self.PageMinimizeButton.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(227, 199, 0);\n"
"border:1px solid rgba(113, 17, 15,50);\n"
"border-radius:6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(139, 29, 31)\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 59, 35);\n"
"}\n"
"")
        self.PageMinimizeButton.setText("")
        self.PageMinimizeButton.setObjectName("PageMinimizeButton")
        self.horizontalLayout.addWidget(self.PageMinimizeButton)
        self.PageMaximizeButton = QtWidgets.QPushButton(self.PageButtonGroup)
        self.PageMaximizeButton.setMinimumSize(QtCore.QSize(12, 12))
        self.PageMaximizeButton.setMaximumSize(QtCore.QSize(12, 12))
        self.PageMaximizeButton.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(4, 180, 0);\n"
"border:1px solid rgba(113, 17, 15,50);\n"
"border-radius:6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(139, 29, 31)\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 59, 35);\n"
"}\n"
"")
        self.PageMaximizeButton.setText("")
        self.PageMaximizeButton.setObjectName("PageMaximizeButton")
        self.horizontalLayout.addWidget(self.PageMaximizeButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.PageButtonGroup)
        self.titleLOGO = QtWidgets.QLabel(self.NavigatePart)
        self.titleLOGO.setMinimumSize(QtCore.QSize(210, 100))
        self.titleLOGO.setMaximumSize(QtCore.QSize(210, 100))
        self.titleLOGO.setText("")
        self.titleLOGO.setPixmap(QtGui.QPixmap("images/teamLogo_white.png"))
        self.titleLOGO.setScaledContents(True)
        self.titleLOGO.setObjectName("titleLOGO")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.titleLOGO)
        self.titleIntro = QtWidgets.QLabel(self.NavigatePart)
        self.titleIntro.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titleIntro.setFont(font)
        self.titleIntro.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.titleIntro.setObjectName("titleIntro")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.titleIntro)
        self.IntroList = QtWidgets.QListWidget(self.NavigatePart)
        self.IntroList.setMinimumSize(QtCore.QSize(0, 0))
        self.IntroList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.IntroList.setFont(font)
        self.IntroList.setStyleSheet("QListView {\n"
"    border-radius: 20px;\n"
"    color: rgba(255, 255, 255,200);\n"
"    background-color: transparent\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"height:40px;\n"
"padding-left:12px;\n"
"}\n"
"QListView::item:hover {\n"
"    background-color: rgba(130, 117, 255, 87);\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    background-color: transparent;\n"
"    background-color: rgba(187, 170, 254,150);\n"
"    color: rgba(255, 255, 255,255);\n"
"border-left: 2px solid rgb(255, 255, 255)\n"
"\n"
"\n"
"}\n"
"")
        self.IntroList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.IntroList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.IntroList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.IntroList.setAutoScrollMargin(16)
        self.IntroList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.IntroList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.IntroList.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.IntroList.setMovement(QtWidgets.QListView.Static)
        self.IntroList.setFlow(QtWidgets.QListView.TopToBottom)
        self.IntroList.setProperty("isWrapping", False)
        self.IntroList.setResizeMode(QtWidgets.QListView.Adjust)
        self.IntroList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.IntroList.setViewMode(QtWidgets.QListView.ListMode)
        self.IntroList.setModelColumn(0)
        self.IntroList.setBatchSize(100)
        self.IntroList.setProperty("IconSize", QtCore.QSize(128, 128))
        self.IntroList.setObjectName("IntroList")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/温室房_green-house.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.IntroList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/沟通_communication.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.IntroList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/个人隐私_personal-privacy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.IntroList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/文档架子_document-folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.IntroList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/交叉环_cross-ring.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.IntroList.addItem(item)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.IntroList)
        self.titleDetails = QtWidgets.QLabel(self.NavigatePart)
        self.titleDetails.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titleDetails.setFont(font)
        self.titleDetails.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.titleDetails.setObjectName("titleDetails")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.titleDetails)
        self.DetailsList = QtWidgets.QListWidget(self.NavigatePart)
        self.DetailsList.setMinimumSize(QtCore.QSize(0, 0))
        self.DetailsList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.DetailsList.setFont(font)
        self.DetailsList.setStyleSheet("QListView {\n"
"    border-radius: 20px;\n"
"    color: rgba(255, 255, 255,200);\n"
"    background-color: transparent\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"height:40px;\n"
"padding-left:12px;\n"
"}\n"
"QListView::item:hover {\n"
"    background-color: rgba(130, 117, 255, 87);\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    background-color: transparent;\n"
"    background-color: rgba(187, 170, 254,150);\n"
"    color: rgba(255, 255, 255,255);\n"
"border-left: 2px solid rgb(255, 255, 255)\n"
"\n"
"\n"
"}\n"
"")
        self.DetailsList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.DetailsList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DetailsList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DetailsList.setAutoScrollMargin(16)
        self.DetailsList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.DetailsList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.DetailsList.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.DetailsList.setMovement(QtWidgets.QListView.Static)
        self.DetailsList.setFlow(QtWidgets.QListView.TopToBottom)
        self.DetailsList.setProperty("isWrapping", False)
        self.DetailsList.setResizeMode(QtWidgets.QListView.Adjust)
        self.DetailsList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.DetailsList.setViewMode(QtWidgets.QListView.ListMode)
        self.DetailsList.setModelColumn(0)
        self.DetailsList.setBatchSize(100)
        self.DetailsList.setProperty("IconSize", QtCore.QSize(128, 128))
        self.DetailsList.setObjectName("DetailsList")
        item = QtWidgets.QListWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/感应锁_induction-lock.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.DetailsList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/上课铃_bell-ring.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        self.DetailsList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/思考问题_thinking-problem.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.DetailsList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/程序问题_bug.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon8)
        self.DetailsList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/保存硬盘_save-one.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon9)
        self.DetailsList.addItem(item)
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.DetailsList)
        self.horizontalLayout_2.addWidget(self.NavigatePart)
        self.DisplayPart = QtWidgets.QFrame(self.TotalPage)
        self.DisplayPart.setStyleSheet("QFrame#DisplayPart{\n"
"border-top-left-radius:0px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"border-bottom-left-radius:0px;\n"
"background-color: rgb(241, 244, 249)\n"
"}")
        self.DisplayPart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DisplayPart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DisplayPart.setObjectName("DisplayPart")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.DisplayPart)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.ChangePage = QtWidgets.QFrame(self.DisplayPart)
        self.ChangePage.setStyleSheet("")
        self.ChangePage.setObjectName("ChangePage")
        self.gridLayout = QtWidgets.QGridLayout(self.ChangePage)
        self.gridLayout.setObjectName("gridLayout")
        self.RightWindowEdge = QtWidgets.QFrame(self.ChangePage)
        self.RightWindowEdge.setMinimumSize(QtCore.QSize(21, 0))
        self.RightWindowEdge.setMaximumSize(QtCore.QSize(21, 16777215))
        self.RightWindowEdge.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.RightWindowEdge.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RightWindowEdge.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RightWindowEdge.setObjectName("RightWindowEdge")
        self.gridLayout.addWidget(self.RightWindowEdge, 1, 1, 1, 1)
        self.SearchBar = QtWidgets.QFrame(self.ChangePage)
        self.SearchBar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:0px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:0px;\n"
"border-bottom-left-radius:0px;")
        self.SearchBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SearchBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SearchBar.setObjectName("SearchBar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.SearchBar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 12, 0)
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.SearchBarLayout = QtWidgets.QHBoxLayout()
        self.SearchBarLayout.setContentsMargins(12, -1, 12, -1)
        self.SearchBarLayout.setSpacing(0)
        self.SearchBarLayout.setObjectName("SearchBarLayout")
        self.SearchLOGO = QtWidgets.QFrame(self.SearchBar)
        self.SearchLOGO.setMinimumSize(QtCore.QSize(18, 18))
        self.SearchLOGO.setMaximumSize(QtCore.QSize(18, 18))
        self.SearchLOGO.setStyleSheet("image: url(:/buttom/img/buttom/搜索_search.svg);")
        self.SearchLOGO.setObjectName("SearchLOGO")
        self.SearchBarLayout.addWidget(self.SearchLOGO)
        self.SearchBarLine = QtWidgets.QLineEdit(self.SearchBar)
        self.SearchBarLine.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.SearchBarLine.setFont(font)
        self.SearchBarLine.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"margin-left:12px;\n"
"border:none;")
        self.SearchBarLine.setText("")
        self.SearchBarLine.setClearButtonEnabled(True)
        self.SearchBarLine.setObjectName("SearchBarLine")
        self.SearchBarLayout.addWidget(self.SearchBarLine)
        self.horizontalLayout_5.addLayout(self.SearchBarLayout)
        self.SearchBarButton = QtWidgets.QPushButton(self.SearchBar)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.SearchBarButton.setFont(font)
        self.SearchBarButton.setStyleSheet("QPushButton:hover {\n"
"border-left: 2px solid rgb(255, 255, 255)\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: transparent;\n"
"background-color: rgba(225, 225, 225,150);\n"
"}")
        self.SearchBarButton.setObjectName("SearchBarButton")
        self.horizontalLayout_5.addWidget(self.SearchBarButton)
        self.SearchBarComboBox = QtWidgets.QComboBox(self.SearchBar)
        self.SearchBarComboBox.setMinimumSize(QtCore.QSize(40, 32))
        self.SearchBarComboBox.setMaximumSize(QtCore.QSize(16777215, 16777))
        self.SearchBarComboBox.setStyleSheet("QComboBox{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"text-align:center;\n"
"padding:8px;\n"
"border-radius:10px\n"
"}\n"
"QComboBox::drop-down{\n"
"    \n"
"    image: url(:/buttom/img/buttom/下_down.svg);\n"
"    width:30px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"    color: rgba(25, 95, 254);\n"
"    gridline-color: rgb(64, 53, 255);\n"
"}\n"
"QComboBox:off{\n"
"    color:  rgb(0, 0, 0);\n"
"}")
        self.SearchBarComboBox.setIconSize(QtCore.QSize(36, 36))
        self.SearchBarComboBox.setObjectName("SearchBarComboBox")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchBarComboBox.addItem(icon10, "")
        self.SearchBarComboBox.setItemText(0, "")
        self.horizontalLayout_5.addWidget(self.SearchBarComboBox)
        self.SearchBarRightLine = QtWidgets.QFrame(self.SearchBar)
        self.SearchBarRightLine.setMaximumSize(QtCore.QSize(1, 16777215))
        self.SearchBarRightLine.setStyleSheet("background-color: rgb(241, 244, 249)")
        self.SearchBarRightLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.SearchBarRightLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SearchBarRightLine.setObjectName("SearchBarRightLine")
        self.horizontalLayout_5.addWidget(self.SearchBarRightLine)
        self.horizontalLayout_5.setStretch(0, 1)
        self.gridLayout.addWidget(self.SearchBar, 0, 0, 1, 2)
        self.DisplayPage = QtWidgets.QStackedWidget(self.ChangePage)
        self.DisplayPage.setObjectName("DisplayPage")
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setObjectName("MainPage")
        self.MainPageFrame = QtWidgets.QFrame(self.MainPage)
        self.MainPageFrame.setGeometry(QtCore.QRect(0, 0, 915, 540))
        self.MainPageFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.MainPageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainPageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainPageFrame.setObjectName("MainPageFrame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.MainPageFrame)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.MainPageBackgroundFrame = QtWidgets.QFrame(self.MainPageFrame)
        self.MainPageBackgroundFrame.setStyleSheet("QFrame#MainPageBackgroundFrame{border-top-left-radius:0px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:10px;\n"
"border-bottom-left-radius:0px;\n"
"    background-color: rgb(241, 244, 249);\n"
"\n"
"}")
        self.MainPageBackgroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainPageBackgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainPageBackgroundFrame.setObjectName("MainPageBackgroundFrame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.MainPageBackgroundFrame)
        self.verticalLayout_14.setContentsMargins(-1, 24, -1, -1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.MainPageTitle = QtWidgets.QLabel(self.MainPageBackgroundFrame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.MainPageTitle.setFont(font)
        self.MainPageTitle.setObjectName("MainPageTitle")
        self.verticalLayout_14.addWidget(self.MainPageTitle)
        self.MainPageLayout1 = QtWidgets.QHBoxLayout()
        self.MainPageLayout1.setSpacing(12)
        self.MainPageLayout1.setObjectName("MainPageLayout1")
        self.FirstFrame = QtWidgets.QFrame(self.MainPageBackgroundFrame)
        self.FirstFrame.setStyleSheet("QFrame#FirstFrame{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(162, 129, 247),  stop:1 rgb(119, 111, 252));\n"
"border: 1px outset rgb(98, 91, 213);\n"
"}\n"
"")
        self.FirstFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FirstFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FirstFrame.setObjectName("FirstFrame")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.FirstFrame)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.FirstFrameButtonFrame = QtWidgets.QFrame(self.FirstFrame)
        self.FirstFrameButtonFrame.setStyleSheet("border:none")
        self.FirstFrameButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FirstFrameButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FirstFrameButtonFrame.setObjectName("FirstFrameButtonFrame")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.FirstFrameButtonFrame)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.FirstFrameButton = QtWidgets.QPushButton(self.FirstFrameButtonFrame)
        self.FirstFrameButton.setMinimumSize(QtCore.QSize(0, 24))
        self.FirstFrameButton.setMaximumSize(QtCore.QSize(41677, 48))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.FirstFrameButton.setFont(font)
        self.FirstFrameButton.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/西瓜视频_xigua.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FirstFrameButton.setIcon(icon11)
        self.FirstFrameButton.setObjectName("FirstFrameButton")
        self.horizontalLayout_15.addWidget(self.FirstFrameButton)
        self.verticalLayout_15.addWidget(self.FirstFrameButtonFrame)
        self.FirstFrameLine = QtWidgets.QFrame(self.FirstFrame)
        self.FirstFrameLine.setMaximumSize(QtCore.QSize(16777215, 1))
        self.FirstFrameLine.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.FirstFrameLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.FirstFrameLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FirstFrameLine.setObjectName("FirstFrameLine")
        self.verticalLayout_15.addWidget(self.FirstFrameLine)
        self.FirstFrameDateFrame = QtWidgets.QFrame(self.FirstFrame)
        self.FirstFrameDateFrame.setStyleSheet("border:none")
        self.FirstFrameDateFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FirstFrameDateFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FirstFrameDateFrame.setObjectName("FirstFrameDateFrame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.FirstFrameDateFrame)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.FirstFrameDate = QtWidgets.QLabel(self.FirstFrameDateFrame)
        self.FirstFrameDate.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.FirstFrameDate.setFont(font)
        self.FirstFrameDate.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.FirstFrameDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.FirstFrameDate.setObjectName("FirstFrameDate")
        self.verticalLayout_16.addWidget(self.FirstFrameDate, 0, QtCore.Qt.AlignBottom)
        self.FirstFrameTime = QtWidgets.QLabel(self.FirstFrameDateFrame)
        self.FirstFrameTime.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setUnderline(False)
        self.FirstFrameTime.setFont(font)
        self.FirstFrameTime.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.FirstFrameTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.FirstFrameTime.setObjectName("FirstFrameTime")
        self.verticalLayout_16.addWidget(self.FirstFrameTime, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_15.addWidget(self.FirstFrameDateFrame)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 4)
        self.verticalLayout_15.setStretch(2, 1)
        self.MainPageLayout1.addWidget(self.FirstFrame)
        self.SecondFrame = QtWidgets.QFrame(self.MainPageBackgroundFrame)
        self.SecondFrame.setStyleSheet("QFrame#SecondFrame{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(253, 139, 133),  stop:1 rgb(248, 194, 152));\n"
"border: 1px outset rgb(252, 194, 149)\n"
"}\n"
"")
        self.SecondFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SecondFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SecondFrame.setObjectName("SecondFrame")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.SecondFrame)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.SecondFrameButtonFrame = QtWidgets.QFrame(self.SecondFrame)
        self.SecondFrameButtonFrame.setStyleSheet("border:none")
        self.SecondFrameButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SecondFrameButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SecondFrameButtonFrame.setObjectName("SecondFrameButtonFrame")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.SecondFrameButtonFrame)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.SecondFrameButton = QtWidgets.QPushButton(self.SecondFrameButtonFrame)
        self.SecondFrameButton.setMinimumSize(QtCore.QSize(0, 24))
        self.SecondFrameButton.setMaximumSize(QtCore.QSize(41677, 48))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.SecondFrameButton.setFont(font)
        self.SecondFrameButton.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        self.SecondFrameButton.setIcon(icon11)
        self.SecondFrameButton.setObjectName("SecondFrameButton")
        self.horizontalLayout_16.addWidget(self.SecondFrameButton)
        self.verticalLayout_17.addWidget(self.SecondFrameButtonFrame)
        self.SecondFrameLine = QtWidgets.QFrame(self.SecondFrame)
        self.SecondFrameLine.setMaximumSize(QtCore.QSize(16777215, 1))
        self.SecondFrameLine.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.SecondFrameLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.SecondFrameLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SecondFrameLine.setObjectName("SecondFrameLine")
        self.verticalLayout_17.addWidget(self.SecondFrameLine)
        self.SecondFrameDateFrame = QtWidgets.QFrame(self.SecondFrame)
        self.SecondFrameDateFrame.setStyleSheet("border:none")
        self.SecondFrameDateFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SecondFrameDateFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SecondFrameDateFrame.setObjectName("SecondFrameDateFrame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.SecondFrameDateFrame)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.SecondFrameDate = QtWidgets.QLabel(self.SecondFrameDateFrame)
        self.SecondFrameDate.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.SecondFrameDate.setFont(font)
        self.SecondFrameDate.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.SecondFrameDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SecondFrameDate.setObjectName("SecondFrameDate")
        self.verticalLayout_18.addWidget(self.SecondFrameDate, 0, QtCore.Qt.AlignBottom)
        self.SecondFrameTime = QtWidgets.QLabel(self.SecondFrameDateFrame)
        self.SecondFrameTime.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setUnderline(False)
        self.SecondFrameTime.setFont(font)
        self.SecondFrameTime.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.SecondFrameTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SecondFrameTime.setObjectName("SecondFrameTime")
        self.verticalLayout_18.addWidget(self.SecondFrameTime, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_17.addWidget(self.SecondFrameDateFrame)
        self.verticalLayout_17.setStretch(0, 1)
        self.verticalLayout_17.setStretch(1, 4)
        self.verticalLayout_17.setStretch(2, 1)
        self.MainPageLayout1.addWidget(self.SecondFrame)
        self.ThirdFrame = QtWidgets.QFrame(self.MainPageBackgroundFrame)
        self.ThirdFrame.setStyleSheet("QFrame#ThirdFrame{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(243, 175, 189),  stop:1 rgb(155, 118, 218));\n"
"border: 1px outset rgb(153, 117, 219)\n"
"}\n"
"")
        self.ThirdFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ThirdFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ThirdFrame.setObjectName("ThirdFrame")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.ThirdFrame)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.ThirdFrameButtonFrame = QtWidgets.QFrame(self.ThirdFrame)
        self.ThirdFrameButtonFrame.setStyleSheet("border:none")
        self.ThirdFrameButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ThirdFrameButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ThirdFrameButtonFrame.setObjectName("ThirdFrameButtonFrame")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.ThirdFrameButtonFrame)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.ThirdFrameButton = QtWidgets.QPushButton(self.ThirdFrameButtonFrame)
        self.ThirdFrameButton.setMinimumSize(QtCore.QSize(0, 24))
        self.ThirdFrameButton.setMaximumSize(QtCore.QSize(41677, 48))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.ThirdFrameButton.setFont(font)
        self.ThirdFrameButton.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        self.ThirdFrameButton.setIcon(icon11)
        self.ThirdFrameButton.setObjectName("ThirdFrameButton")
        self.horizontalLayout_17.addWidget(self.ThirdFrameButton)
        self.verticalLayout_19.addWidget(self.ThirdFrameButtonFrame)
        self.ThirdFrameLine = QtWidgets.QFrame(self.ThirdFrame)
        self.ThirdFrameLine.setMaximumSize(QtCore.QSize(16777215, 1))
        self.ThirdFrameLine.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.ThirdFrameLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.ThirdFrameLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ThirdFrameLine.setObjectName("ThirdFrameLine")
        self.verticalLayout_19.addWidget(self.ThirdFrameLine)
        self.ThirdFrameDateFrame = QtWidgets.QFrame(self.ThirdFrame)
        self.ThirdFrameDateFrame.setStyleSheet("border:none")
        self.ThirdFrameDateFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ThirdFrameDateFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ThirdFrameDateFrame.setObjectName("ThirdFrameDateFrame")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.ThirdFrameDateFrame)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.ThirdFrameDate = QtWidgets.QLabel(self.ThirdFrameDateFrame)
        self.ThirdFrameDate.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ThirdFrameDate.setFont(font)
        self.ThirdFrameDate.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.ThirdFrameDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ThirdFrameDate.setObjectName("ThirdFrameDate")
        self.verticalLayout_20.addWidget(self.ThirdFrameDate, 0, QtCore.Qt.AlignBottom)
        self.ThirdFrameTime = QtWidgets.QLabel(self.ThirdFrameDateFrame)
        self.ThirdFrameTime.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setUnderline(False)
        self.ThirdFrameTime.setFont(font)
        self.ThirdFrameTime.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.ThirdFrameTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ThirdFrameTime.setObjectName("ThirdFrameTime")
        self.verticalLayout_20.addWidget(self.ThirdFrameTime, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_19.addWidget(self.ThirdFrameDateFrame)
        self.verticalLayout_19.setStretch(0, 1)
        self.verticalLayout_19.setStretch(1, 4)
        self.verticalLayout_19.setStretch(2, 1)
        self.MainPageLayout1.addWidget(self.ThirdFrame)
        self.FourthFrame = QtWidgets.QFrame(self.MainPageBackgroundFrame)
        self.FourthFrame.setStyleSheet("QFrame#FourthFrame{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(66, 226, 192),  stop:1 rgb(62, 154, 193));\n"
"border: 1px outset rgb(72, 158, 204)\n"
"}\n"
"")
        self.FourthFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FourthFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FourthFrame.setObjectName("FourthFrame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.FourthFrame)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.FourthFrameButtonFrame = QtWidgets.QFrame(self.FourthFrame)
        self.FourthFrameButtonFrame.setStyleSheet("border:none")
        self.FourthFrameButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FourthFrameButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FourthFrameButtonFrame.setObjectName("FourthFrameButtonFrame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.FourthFrameButtonFrame)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.FourthFrameButton = QtWidgets.QPushButton(self.FourthFrameButtonFrame)
        self.FourthFrameButton.setMinimumSize(QtCore.QSize(0, 24))
        self.FourthFrameButton.setMaximumSize(QtCore.QSize(41677, 48))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.FourthFrameButton.setFont(font)
        self.FourthFrameButton.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        self.FourthFrameButton.setIcon(icon11)
        self.FourthFrameButton.setObjectName("FourthFrameButton")
        self.horizontalLayout_18.addWidget(self.FourthFrameButton)
        self.verticalLayout_21.addWidget(self.FourthFrameButtonFrame)
        self.FourthFrameLine = QtWidgets.QFrame(self.FourthFrame)
        self.FourthFrameLine.setMaximumSize(QtCore.QSize(16777215, 1))
        self.FourthFrameLine.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.FourthFrameLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.FourthFrameLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FourthFrameLine.setObjectName("FourthFrameLine")
        self.verticalLayout_21.addWidget(self.FourthFrameLine)
        self.FourthFrameDateFrame = QtWidgets.QFrame(self.FourthFrame)
        self.FourthFrameDateFrame.setStyleSheet("border:none")
        self.FourthFrameDateFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FourthFrameDateFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FourthFrameDateFrame.setObjectName("FourthFrameDateFrame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.FourthFrameDateFrame)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.FourthFrameDate = QtWidgets.QLabel(self.FourthFrameDateFrame)
        self.FourthFrameDate.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.FourthFrameDate.setFont(font)
        self.FourthFrameDate.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.FourthFrameDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.FourthFrameDate.setObjectName("FourthFrameDate")
        self.verticalLayout_22.addWidget(self.FourthFrameDate)
        self.FourthFrameTime = QtWidgets.QLabel(self.FourthFrameDateFrame)
        self.FourthFrameTime.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setUnderline(False)
        self.FourthFrameTime.setFont(font)
        self.FourthFrameTime.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.FourthFrameTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.FourthFrameTime.setObjectName("FourthFrameTime")
        self.verticalLayout_22.addWidget(self.FourthFrameTime)
        self.verticalLayout_21.addWidget(self.FourthFrameDateFrame)
        self.verticalLayout_21.setStretch(1, 4)
        self.MainPageLayout1.addWidget(self.FourthFrame)
        self.verticalLayout_14.addLayout(self.MainPageLayout1)
        self.MainPageLayout2 = QtWidgets.QVBoxLayout()
        self.MainPageLayout2.setSpacing(0)
        self.MainPageLayout2.setObjectName("MainPageLayout2")
        self.MainPageChooseLayout = QtWidgets.QHBoxLayout()
        self.MainPageChooseLayout.setSpacing(12)
        self.MainPageChooseLayout.setObjectName("MainPageChooseLayout")
        self.MainPageChooseTitle = QtWidgets.QLabel(self.MainPageBackgroundFrame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.MainPageChooseTitle.setFont(font)
        self.MainPageChooseTitle.setStyleSheet("")
        self.MainPageChooseTitle.setObjectName("MainPageChooseTitle")
        self.MainPageChooseLayout.addWidget(self.MainPageChooseTitle)
        self.MainPageChooseList = QtWidgets.QListWidget(self.MainPageBackgroundFrame)
        self.MainPageChooseList.setMinimumSize(QtCore.QSize(0, 0))
        self.MainPageChooseList.setMaximumSize(QtCore.QSize(16777, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.MainPageChooseList.setFont(font)
        self.MainPageChooseList.setStyleSheet("QListView {\n"
"    border-radius: 20px;\n"
"    color: rgba(106, 106, 106,200);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"height:40px;\n"
"}\n"
"QListView::item:hover {\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    /*background-color: transparent;*/\n"
"    color: rgb(16, 15, 35);\n"
"border-bottom: 3px solid rgb(119, 111, 255)\n"
"\n"
"\n"
"}\n"
"")
        self.MainPageChooseList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainPageChooseList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.MainPageChooseList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.MainPageChooseList.setAutoScrollMargin(16)
        self.MainPageChooseList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.MainPageChooseList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.MainPageChooseList.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.MainPageChooseList.setMovement(QtWidgets.QListView.Static)
        self.MainPageChooseList.setFlow(QtWidgets.QListView.LeftToRight)
        self.MainPageChooseList.setProperty("isWrapping", False)
        self.MainPageChooseList.setResizeMode(QtWidgets.QListView.Adjust)
        self.MainPageChooseList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.MainPageChooseList.setViewMode(QtWidgets.QListView.ListMode)
        self.MainPageChooseList.setModelColumn(0)
        self.MainPageChooseList.setBatchSize(100)
        self.MainPageChooseList.setProperty("IconSize", QtCore.QSize(128, 128))
        self.MainPageChooseList.setObjectName("MainPageChooseList")
        item = QtWidgets.QListWidgetItem()
        self.MainPageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.MainPageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.MainPageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.MainPageChooseList.addItem(item)
        self.MainPageChooseLayout.addWidget(self.MainPageChooseList)
        self.MainPageLayout2.addLayout(self.MainPageChooseLayout)
        self.MainWeb = QtWebEngineWidgets.QWebEngineView(self.MainPageBackgroundFrame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.MainWeb.setFont(font)
        self.MainWeb.setStyleSheet("QWidget{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    selection-background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QWebEngineView{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    selection-background-color: rgba(0, 0, 0, 0);\n"
"\n"
"}")
        self.MainWeb.setProperty("url", QtCore.QUrl("file:///C:/Users/10542/Desktop/UESTC/UI/htmls/enterprise_bar.html"))
        self.MainWeb.setObjectName("MainWeb")
        self.MainPageLayout2.addWidget(self.MainWeb)
        self.MainPageLayout2.setStretch(1, 1)
        self.verticalLayout_14.addLayout(self.MainPageLayout2)
        self.verticalLayout_14.setStretch(1, 1)
        self.verticalLayout_14.setStretch(2, 3)
        self.horizontalLayout_13.addWidget(self.MainPageBackgroundFrame)
        self.DisplayPage.addWidget(self.MainPage)
        self.SearchPage = QtWidgets.QWidget()
        self.SearchPage.setObjectName("SearchPage")
        self.SearchPageFrame = QtWidgets.QFrame(self.SearchPage)
        self.SearchPageFrame.setGeometry(QtCore.QRect(11, 11, 915, 540))
        self.SearchPageFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.SearchPageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SearchPageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SearchPageFrame.setObjectName("SearchPageFrame")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.SearchPageFrame)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.SearchPageBackgroundFrame = QtWidgets.QFrame(self.SearchPageFrame)
        self.SearchPageBackgroundFrame.setStyleSheet("QFrame#SearchPageBackgroundFrame{border-top-left-radius:0px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:10px;\n"
"border-bottom-left-radius:0px;\n"
"    background-color: rgb(241, 244, 249);\n"
"\n"
"}")
        self.SearchPageBackgroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SearchPageBackgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SearchPageBackgroundFrame.setObjectName("SearchPageBackgroundFrame")
        self.SearchPageTitle = QtWidgets.QLabel(self.SearchPageBackgroundFrame)
        self.SearchPageTitle.setGeometry(QtCore.QRect(0, 10, 317, 33))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.SearchPageTitle.setFont(font)
        self.SearchPageTitle.setObjectName("SearchPageTitle")
        self.SearchWeb = QtWebEngineWidgets.QWebEngineView(self.SearchPageBackgroundFrame)
        self.SearchWeb.setGeometry(QtCore.QRect(10, 110, 800, 450))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.SearchWeb.setFont(font)
        self.SearchWeb.setStyleSheet("QWebEngineView#webEngineView3{\n"
"    rgb(255, 255, 255)\n"
"}")
        self.SearchWeb.setProperty("url", QtCore.QUrl("file:///C:/Users/10542/Desktop/UESTC/UI/htmls/enterprise_bar.html"))
        self.SearchWeb.setObjectName("SearchWeb")
        self.layoutWidget_2 = QtWidgets.QWidget(self.SearchPageBackgroundFrame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 50, 781, 52))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.SearchPageChooseLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.SearchPageChooseLayout.setContentsMargins(0, 0, 0, 0)
        self.SearchPageChooseLayout.setSpacing(12)
        self.SearchPageChooseLayout.setObjectName("SearchPageChooseLayout")
        self.SearchPageChooseLayoutLable = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.SearchPageChooseLayoutLable.setFont(font)
        self.SearchPageChooseLayoutLable.setStyleSheet("")
        self.SearchPageChooseLayoutLable.setObjectName("SearchPageChooseLayoutLable")
        self.SearchPageChooseLayout.addWidget(self.SearchPageChooseLayoutLable)
        self.SearchPageChooseList = QtWidgets.QListWidget(self.layoutWidget_2)
        self.SearchPageChooseList.setMinimumSize(QtCore.QSize(0, 0))
        self.SearchPageChooseList.setMaximumSize(QtCore.QSize(16777, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.SearchPageChooseList.setFont(font)
        self.SearchPageChooseList.setTabletTracking(False)
        self.SearchPageChooseList.setStyleSheet("QListView {\n"
"    border-radius: 20px;\n"
"    color: rgba(106, 106, 106,200);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"height:40px;\n"
"}\n"
"QListView::item:hover {\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    /*background-color: transparent;*/\n"
"    color: rgb(16, 15, 35);\n"
"border-bottom: 3px solid rgb(119, 111, 255)\n"
"\n"
"\n"
"}\n"
"")
        self.SearchPageChooseList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SearchPageChooseList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SearchPageChooseList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SearchPageChooseList.setAutoScrollMargin(16)
        self.SearchPageChooseList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.SearchPageChooseList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.SearchPageChooseList.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.SearchPageChooseList.setMovement(QtWidgets.QListView.Static)
        self.SearchPageChooseList.setFlow(QtWidgets.QListView.LeftToRight)
        self.SearchPageChooseList.setProperty("isWrapping", False)
        self.SearchPageChooseList.setResizeMode(QtWidgets.QListView.Adjust)
        self.SearchPageChooseList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.SearchPageChooseList.setViewMode(QtWidgets.QListView.ListMode)
        self.SearchPageChooseList.setModelColumn(0)
        self.SearchPageChooseList.setBatchSize(100)
        self.SearchPageChooseList.setProperty("IconSize", QtCore.QSize(128, 128))
        self.SearchPageChooseList.setObjectName("SearchPageChooseList")
        item = QtWidgets.QListWidgetItem()
        self.SearchPageChooseList.addItem(item)
        self.SearchPageChooseLayout.addWidget(self.SearchPageChooseList)
        self.horizontalLayout_28.addWidget(self.SearchPageBackgroundFrame)
        self.DisplayPage.addWidget(self.SearchPage)
        self.BarPage = QtWidgets.QWidget()
        self.BarPage.setObjectName("BarPage")
        self.BarPageFrame = QtWidgets.QFrame(self.BarPage)
        self.BarPageFrame.setGeometry(QtCore.QRect(11, 11, 915, 540))
        self.BarPageFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.BarPageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BarPageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BarPageFrame.setObjectName("BarPageFrame")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.BarPageFrame)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.BarPageBackgroundFrame = QtWidgets.QFrame(self.BarPageFrame)
        self.BarPageBackgroundFrame.setStyleSheet("QFrame#BarPageBackgroundFrame{border-top-left-radius:0px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:10px;\n"
"border-bottom-left-radius:0px;\n"
"    background-color: rgb(241, 244, 249);\n"
"\n"
"}")
        self.BarPageBackgroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BarPageBackgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BarPageBackgroundFrame.setObjectName("BarPageBackgroundFrame")
        self.BarPageTitle = QtWidgets.QLabel(self.BarPageBackgroundFrame)
        self.BarPageTitle.setGeometry(QtCore.QRect(0, 10, 317, 33))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.BarPageTitle.setFont(font)
        self.BarPageTitle.setObjectName("BarPageTitle")
        self.BarWeb = QtWebEngineWidgets.QWebEngineView(self.BarPageBackgroundFrame)
        self.BarWeb.setGeometry(QtCore.QRect(10, 110, 800, 450))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.BarWeb.setFont(font)
        self.BarWeb.setStyleSheet("QWebEngineView#webEngineView3{\n"
"    rgb(255, 255, 255)\n"
"}")
        self.BarWeb.setProperty("url", QtCore.QUrl("file:///C:/Users/10542/Desktop/UESTC/UI/htmls/enterprise_bar.html"))
        self.BarWeb.setObjectName("BarWeb")
        self.layoutWidget_3 = QtWidgets.QWidget(self.BarPageBackgroundFrame)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 50, 781, 52))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.BarPageChooseLayout = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.BarPageChooseLayout.setContentsMargins(0, 0, 0, 0)
        self.BarPageChooseLayout.setSpacing(12)
        self.BarPageChooseLayout.setObjectName("BarPageChooseLayout")
        self.BarPageChooseLayoutLable = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.BarPageChooseLayoutLable.setFont(font)
        self.BarPageChooseLayoutLable.setStyleSheet("")
        self.BarPageChooseLayoutLable.setObjectName("BarPageChooseLayoutLable")
        self.BarPageChooseLayout.addWidget(self.BarPageChooseLayoutLable)
        self.BarPageChooseList = QtWidgets.QListWidget(self.layoutWidget_3)
        self.BarPageChooseList.setMinimumSize(QtCore.QSize(0, 0))
        self.BarPageChooseList.setMaximumSize(QtCore.QSize(16777, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.BarPageChooseList.setFont(font)
        self.BarPageChooseList.setTabletTracking(False)
        self.BarPageChooseList.setStyleSheet("QListView {\n"
"    border-radius: 20px;\n"
"    color: rgba(106, 106, 106,200);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"height:40px;\n"
"}\n"
"QListView::item:hover {\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    /*background-color: transparent;*/\n"
"    color: rgb(16, 15, 35);\n"
"border-bottom: 3px solid rgb(119, 111, 255)\n"
"\n"
"\n"
"}\n"
"")
        self.BarPageChooseList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BarPageChooseList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.BarPageChooseList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.BarPageChooseList.setAutoScrollMargin(16)
        self.BarPageChooseList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.BarPageChooseList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.BarPageChooseList.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.BarPageChooseList.setMovement(QtWidgets.QListView.Static)
        self.BarPageChooseList.setFlow(QtWidgets.QListView.LeftToRight)
        self.BarPageChooseList.setProperty("isWrapping", False)
        self.BarPageChooseList.setResizeMode(QtWidgets.QListView.Adjust)
        self.BarPageChooseList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.BarPageChooseList.setViewMode(QtWidgets.QListView.ListMode)
        self.BarPageChooseList.setModelColumn(0)
        self.BarPageChooseList.setBatchSize(100)
        self.BarPageChooseList.setProperty("IconSize", QtCore.QSize(128, 128))
        self.BarPageChooseList.setObjectName("BarPageChooseList")
        item = QtWidgets.QListWidgetItem()
        self.BarPageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.BarPageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.BarPageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.BarPageChooseList.addItem(item)
        self.BarPageChooseLayout.addWidget(self.BarPageChooseList)
        self.horizontalLayout_27.addWidget(self.BarPageBackgroundFrame)
        self.DisplayPage.addWidget(self.BarPage)
        self.PiePage = QtWidgets.QWidget()
        self.PiePage.setObjectName("PiePage")
        self.PiePageFrame = QtWidgets.QFrame(self.PiePage)
        self.PiePageFrame.setGeometry(QtCore.QRect(11, 11, 915, 540))
        self.PiePageFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.PiePageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PiePageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PiePageFrame.setObjectName("PiePageFrame")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.PiePageFrame)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.PiePageBackgroundFrame = QtWidgets.QFrame(self.PiePageFrame)
        self.PiePageBackgroundFrame.setStyleSheet("QFrame#PiePageBackgroundFrame{border-top-left-radius:0px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:10px;\n"
"border-bottom-left-radius:0px;\n"
"    background-color: rgb(241, 244, 249);\n"
"\n"
"}")
        self.PiePageBackgroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PiePageBackgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PiePageBackgroundFrame.setObjectName("PiePageBackgroundFrame")
        self.PiePageTitle = QtWidgets.QLabel(self.PiePageBackgroundFrame)
        self.PiePageTitle.setGeometry(QtCore.QRect(0, 10, 317, 33))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PiePageTitle.setFont(font)
        self.PiePageTitle.setObjectName("PiePageTitle")
        self.PieWeb = QtWebEngineWidgets.QWebEngineView(self.PiePageBackgroundFrame)
        self.PieWeb.setGeometry(QtCore.QRect(10, 110, 800, 450))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.PieWeb.setFont(font)
        self.PieWeb.setStyleSheet("QWebEngineView#webEngineView3{\n"
"    rgb(255, 255, 255)\n"
"}")
        self.PieWeb.setProperty("url", QtCore.QUrl("file://c/Users/10542/Desktop/UESTC/UI/htmls/industry_bar.html"))
        self.PieWeb.setObjectName("PieWeb")
        self.layoutWidget = QtWidgets.QWidget(self.PiePageBackgroundFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 50, 781, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.PiePageChooseLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.PiePageChooseLayout.setContentsMargins(0, 0, 0, 0)
        self.PiePageChooseLayout.setSpacing(12)
        self.PiePageChooseLayout.setObjectName("PiePageChooseLayout")
        self.PiePageChooseLayoutLable = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.PiePageChooseLayoutLable.setFont(font)
        self.PiePageChooseLayoutLable.setStyleSheet("")
        self.PiePageChooseLayoutLable.setObjectName("PiePageChooseLayoutLable")
        self.PiePageChooseLayout.addWidget(self.PiePageChooseLayoutLable)
        self.PiePageChooseList = QtWidgets.QListWidget(self.layoutWidget)
        self.PiePageChooseList.setMinimumSize(QtCore.QSize(0, 0))
        self.PiePageChooseList.setMaximumSize(QtCore.QSize(16777, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.PiePageChooseList.setFont(font)
        self.PiePageChooseList.setTabletTracking(False)
        self.PiePageChooseList.setStyleSheet("QListView {\n"
"    border-radius: 20px;\n"
"    color: rgba(106, 106, 106,200);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"height:40px;\n"
"}\n"
"QListView::item:hover {\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    /*background-color: transparent;*/\n"
"    color: rgb(16, 15, 35);\n"
"border-bottom: 3px solid rgb(119, 111, 255)\n"
"\n"
"\n"
"}\n"
"")
        self.PiePageChooseList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.PiePageChooseList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.PiePageChooseList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.PiePageChooseList.setAutoScrollMargin(16)
        self.PiePageChooseList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.PiePageChooseList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.PiePageChooseList.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.PiePageChooseList.setMovement(QtWidgets.QListView.Static)
        self.PiePageChooseList.setFlow(QtWidgets.QListView.LeftToRight)
        self.PiePageChooseList.setProperty("isWrapping", False)
        self.PiePageChooseList.setResizeMode(QtWidgets.QListView.Adjust)
        self.PiePageChooseList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.PiePageChooseList.setViewMode(QtWidgets.QListView.ListMode)
        self.PiePageChooseList.setModelColumn(0)
        self.PiePageChooseList.setBatchSize(100)
        self.PiePageChooseList.setProperty("IconSize", QtCore.QSize(128, 128))
        self.PiePageChooseList.setObjectName("PiePageChooseList")
        item = QtWidgets.QListWidgetItem()
        self.PiePageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.PiePageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.PiePageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.PiePageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.PiePageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.PiePageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.PiePageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.PiePageChooseList.addItem(item)
        self.PiePageChooseLayout.addWidget(self.PiePageChooseList)
        self.horizontalLayout_26.addWidget(self.PiePageBackgroundFrame)
        self.DisplayPage.addWidget(self.PiePage)
        self.GraphPage = QtWidgets.QWidget()
        self.GraphPage.setObjectName("GraphPage")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.GraphPage)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.GraphPageFrame = QtWidgets.QFrame(self.GraphPage)
        self.GraphPageFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.GraphPageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GraphPageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GraphPageFrame.setObjectName("GraphPageFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.GraphPageFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.GraphPageBackgroundFrame = QtWidgets.QFrame(self.GraphPageFrame)
        self.GraphPageBackgroundFrame.setStyleSheet("QFrame#GraphPageBackgroundFrame{border-top-left-radius:0px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:10px;\n"
"border-bottom-left-radius:0px;\n"
"    background-color: rgb(241, 244, 249);\n"
"\n"
"}")
        self.GraphPageBackgroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GraphPageBackgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GraphPageBackgroundFrame.setObjectName("GraphPageBackgroundFrame")
        self.GraphPageTitle = QtWidgets.QLabel(self.GraphPageBackgroundFrame)
        self.GraphPageTitle.setGeometry(QtCore.QRect(0, 10, 317, 33))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.GraphPageTitle.setFont(font)
        self.GraphPageTitle.setObjectName("GraphPageTitle")
        self.GraphWeb = QtWebEngineWidgets.QWebEngineView(self.GraphPageBackgroundFrame)
        self.GraphWeb.setGeometry(QtCore.QRect(10, 110, 800, 450))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.GraphWeb.setFont(font)
        self.GraphWeb.setStyleSheet("QWebEngineView#webEngineView3{\n"
"    rgb(255, 255, 255)\n"
"}")
        self.GraphWeb.setProperty("url", QtCore.QUrl("file:///C:/Users/10542/Desktop/UESTC/UI/htmls/enterprise_bar.html"))
        self.GraphWeb.setObjectName("GraphWeb")
        self.layoutWidget1 = QtWidgets.QWidget(self.GraphPageBackgroundFrame)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 50, 781, 52))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.GraphPageChooseLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.GraphPageChooseLayout.setContentsMargins(0, 0, 0, 0)
        self.GraphPageChooseLayout.setSpacing(12)
        self.GraphPageChooseLayout.setObjectName("GraphPageChooseLayout")
        self.GraphPageChooseLayoutLable = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.GraphPageChooseLayoutLable.setFont(font)
        self.GraphPageChooseLayoutLable.setStyleSheet("")
        self.GraphPageChooseLayoutLable.setObjectName("GraphPageChooseLayoutLable")
        self.GraphPageChooseLayout.addWidget(self.GraphPageChooseLayoutLable)
        self.GraphPageChooseList = QtWidgets.QListWidget(self.layoutWidget1)
        self.GraphPageChooseList.setMinimumSize(QtCore.QSize(0, 0))
        self.GraphPageChooseList.setMaximumSize(QtCore.QSize(16777, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.GraphPageChooseList.setFont(font)
        self.GraphPageChooseList.setStyleSheet("QListView {\n"
"    border-radius: 20px;\n"
"    color: rgba(106, 106, 106,200);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"height:40px;\n"
"}\n"
"QListView::item:hover {\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    /*background-color: transparent;*/\n"
"    color: rgb(16, 15, 35);\n"
"border-bottom: 3px solid rgb(119, 111, 255)\n"
"\n"
"\n"
"}\n"
"")
        self.GraphPageChooseList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.GraphPageChooseList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.GraphPageChooseList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.GraphPageChooseList.setAutoScrollMargin(16)
        self.GraphPageChooseList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.GraphPageChooseList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.GraphPageChooseList.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.GraphPageChooseList.setMovement(QtWidgets.QListView.Static)
        self.GraphPageChooseList.setFlow(QtWidgets.QListView.LeftToRight)
        self.GraphPageChooseList.setProperty("isWrapping", False)
        self.GraphPageChooseList.setResizeMode(QtWidgets.QListView.Adjust)
        self.GraphPageChooseList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.GraphPageChooseList.setViewMode(QtWidgets.QListView.ListMode)
        self.GraphPageChooseList.setModelColumn(0)
        self.GraphPageChooseList.setBatchSize(100)
        self.GraphPageChooseList.setProperty("IconSize", QtCore.QSize(128, 128))
        self.GraphPageChooseList.setObjectName("GraphPageChooseList")
        item = QtWidgets.QListWidgetItem()
        self.GraphPageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.GraphPageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.GraphPageChooseList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.GraphPageChooseList.addItem(item)
        self.GraphPageChooseLayout.addWidget(self.GraphPageChooseList)
        self.horizontalLayout_3.addWidget(self.GraphPageBackgroundFrame)
        self.horizontalLayout_12.addWidget(self.GraphPageFrame)
        self.DisplayPage.addWidget(self.GraphPage)
        self.EmptyPage = QtWidgets.QWidget()
        self.EmptyPage.setObjectName("EmptyPage")
        self.DisplayPage.addWidget(self.EmptyPage)
        self.gridLayout.addWidget(self.DisplayPage, 1, 0, 1, 1)
        self.WindowEdgeLayout = QtWidgets.QHBoxLayout()
        self.WindowEdgeLayout.setSpacing(0)
        self.WindowEdgeLayout.setObjectName("WindowEdgeLayout")
        self.BottomWindowEdge = QtWidgets.QFrame(self.ChangePage)
        self.BottomWindowEdge.setMinimumSize(QtCore.QSize(0, 21))
        self.BottomWindowEdge.setMaximumSize(QtCore.QSize(16777215, 21))
        self.BottomWindowEdge.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.BottomWindowEdge.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BottomWindowEdge.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BottomWindowEdge.setObjectName("BottomWindowEdge")
        self.WindowEdgeLayout.addWidget(self.BottomWindowEdge)
        self.gridLayout.addLayout(self.WindowEdgeLayout, 3, 0, 1, 1)
        self.RightBottomWindowEdge = QtWidgets.QFrame(self.ChangePage)
        self.RightBottomWindowEdge.setMinimumSize(QtCore.QSize(21, 21))
        self.RightBottomWindowEdge.setMaximumSize(QtCore.QSize(21, 21))
        self.RightBottomWindowEdge.setCursor(QtGui.QCursor(QtCore.Qt.SizeFDiagCursor))
        self.RightBottomWindowEdge.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RightBottomWindowEdge.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RightBottomWindowEdge.setObjectName("RightBottomWindowEdge")
        self.gridLayout.addWidget(self.RightBottomWindowEdge, 3, 1, 1, 1)
        self.verticalLayout_12.addWidget(self.ChangePage)
        self.horizontalLayout_2.addWidget(self.DisplayPart)
        self.horizontalLayout_2.setStretch(1, 4)
        self.DisplayPart.raise_()
        self.NavigatePart.raise_()
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.TotalPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.IntroList.setCurrentRow(-1)
        self.DetailsList.setCurrentRow(-1)
        self.DisplayPage.setCurrentIndex(0)
        self.MainPageChooseList.setCurrentRow(2)
        self.SearchPageChooseList.setCurrentRow(-1)
        self.BarPageChooseList.setCurrentRow(-1)
        self.PiePageChooseList.setCurrentRow(-1)
        self.GraphPageChooseList.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLOGO.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.titleIntro.setText(_translate("MainWindow", "INTRO"))
        self.IntroList.setSortingEnabled(False)
        __sortingEnabled = self.IntroList.isSortingEnabled()
        self.IntroList.setSortingEnabled(False)
        item = self.IntroList.item(0)
        item.setText(_translate("MainWindow", "Mainpage"))
        item = self.IntroList.item(1)
        item.setText(_translate("MainWindow", "Communication"))
        item = self.IntroList.item(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.IntroList.item(3)
        item.setText(_translate("MainWindow", "Document"))
        item = self.IntroList.item(4)
        item.setText(_translate("MainWindow", "Interactive"))
        self.IntroList.setSortingEnabled(__sortingEnabled)
        self.titleDetails.setText(_translate("MainWindow", "DETAILS"))
        self.DetailsList.setSortingEnabled(False)
        __sortingEnabled = self.DetailsList.isSortingEnabled()
        self.DetailsList.setSortingEnabled(False)
        item = self.DetailsList.item(0)
        item.setText(_translate("MainWindow", "Bar"))
        item = self.DetailsList.item(1)
        item.setText(_translate("MainWindow", "Pie"))
        item = self.DetailsList.item(2)
        item.setText(_translate("MainWindow", "Graph"))
        item = self.DetailsList.item(3)
        item.setText(_translate("MainWindow", "Alert"))
        item = self.DetailsList.item(4)
        item.setText(_translate("MainWindow", "Preservation"))
        self.DetailsList.setSortingEnabled(__sortingEnabled)
        self.SearchBarLine.setPlaceholderText(_translate("MainWindow", "Search Type"))
        self.SearchBarButton.setText(_translate("MainWindow", "Search"))
        self.MainPageTitle.setText(_translate("MainWindow", "Realtime Message Data"))
        self.FirstFrameButton.setText(_translate("MainWindow", "Videoconferencing"))
        self.FirstFrameDate.setText(_translate("MainWindow", "March 27th 2019"))
        self.FirstFrameTime.setText(_translate("MainWindow", "12:26:05 pn UTC-07:00"))
        self.SecondFrameButton.setText(_translate("MainWindow", "Videoconferencing"))
        self.SecondFrameDate.setText(_translate("MainWindow", "March 27th 2019"))
        self.SecondFrameTime.setText(_translate("MainWindow", "12:26:05 pn UTC-07:00"))
        self.ThirdFrameButton.setText(_translate("MainWindow", "Videoconferencing"))
        self.ThirdFrameDate.setText(_translate("MainWindow", "March 27th 2019"))
        self.ThirdFrameTime.setText(_translate("MainWindow", "12:26:05 pn UTC-07:00"))
        self.FourthFrameButton.setText(_translate("MainWindow", "Videoconferencing"))
        self.FourthFrameDate.setText(_translate("MainWindow", "March 27th 2019"))
        self.FourthFrameTime.setText(_translate("MainWindow", "12:26:05 pn UTC-07:00"))
        self.MainPageChooseTitle.setText(_translate("MainWindow", "Choose your data"))
        self.MainPageChooseList.setSortingEnabled(False)
        __sortingEnabled = self.MainPageChooseList.isSortingEnabled()
        self.MainPageChooseList.setSortingEnabled(False)
        item = self.MainPageChooseList.item(0)
        item.setText(_translate("MainWindow", "Last 120 second"))
        item = self.MainPageChooseList.item(1)
        item.setText(_translate("MainWindow", "Last 30 minute"))
        item = self.MainPageChooseList.item(2)
        item.setText(_translate("MainWindow", "Last 24 hours"))
        item = self.MainPageChooseList.item(3)
        item.setText(_translate("MainWindow", "Last 5 days"))
        self.MainPageChooseList.setSortingEnabled(__sortingEnabled)
        self.SearchPageTitle.setText(_translate("MainWindow", "Search Resuts"))
        self.SearchPageChooseLayoutLable.setText(_translate("MainWindow", "Choose your data"))
        self.SearchPageChooseList.setSortingEnabled(False)
        __sortingEnabled = self.SearchPageChooseList.isSortingEnabled()
        self.SearchPageChooseList.setSortingEnabled(False)
        item = self.SearchPageChooseList.item(0)
        item.setText(_translate("MainWindow", "show the result"))
        self.SearchPageChooseList.setSortingEnabled(__sortingEnabled)
        self.BarPageTitle.setText(_translate("MainWindow", "BarPage"))
        self.BarPageChooseLayoutLable.setText(_translate("MainWindow", "Choose your data"))
        self.BarPageChooseList.setSortingEnabled(False)
        __sortingEnabled = self.BarPageChooseList.isSortingEnabled()
        self.BarPageChooseList.setSortingEnabled(False)
        item = self.BarPageChooseList.item(0)
        item.setText(_translate("MainWindow", "Bar 1"))
        item = self.BarPageChooseList.item(1)
        item.setText(_translate("MainWindow", "Bar 2"))
        item = self.BarPageChooseList.item(2)
        item.setText(_translate("MainWindow", "Bar 3"))
        item = self.BarPageChooseList.item(3)
        item.setText(_translate("MainWindow", "Bar 4"))
        self.BarPageChooseList.setSortingEnabled(__sortingEnabled)
        self.PiePageTitle.setText(_translate("MainWindow", "PiePage"))
        self.PiePageChooseLayoutLable.setText(_translate("MainWindow", "Choose your data"))
        self.PiePageChooseList.setSortingEnabled(False)
        __sortingEnabled = self.PiePageChooseList.isSortingEnabled()
        self.PiePageChooseList.setSortingEnabled(False)
        item = self.PiePageChooseList.item(0)
        item.setText(_translate("MainWindow", "Pie 1"))
        item = self.PiePageChooseList.item(1)
        item.setText(_translate("MainWindow", "Pie 2"))
        item = self.PiePageChooseList.item(2)
        item.setText(_translate("MainWindow", "Pie 3"))
        item = self.PiePageChooseList.item(3)
        item.setText(_translate("MainWindow", "Pie 4"))
        item = self.PiePageChooseList.item(4)
        item.setText(_translate("MainWindow", "Pie 5"))
        item = self.PiePageChooseList.item(5)
        item.setText(_translate("MainWindow", "Pie 6"))
        item = self.PiePageChooseList.item(6)
        item.setText(_translate("MainWindow", "Pie 7"))
        item = self.PiePageChooseList.item(7)
        item.setText(_translate("MainWindow", "Pie 8"))
        self.PiePageChooseList.setSortingEnabled(__sortingEnabled)
        self.GraphPageTitle.setText(_translate("MainWindow", "Graph Page"))
        self.GraphPageChooseLayoutLable.setText(_translate("MainWindow", "Choose your data"))
        self.GraphPageChooseList.setSortingEnabled(False)
        __sortingEnabled = self.GraphPageChooseList.isSortingEnabled()
        self.GraphPageChooseList.setSortingEnabled(False)
        item = self.GraphPageChooseList.item(0)
        item.setText(_translate("MainWindow", "Graph 1"))
        item = self.GraphPageChooseList.item(1)
        item.setText(_translate("MainWindow", "Graph 2"))
        item = self.GraphPageChooseList.item(2)
        item.setText(_translate("MainWindow", "Graph 3"))
        item = self.GraphPageChooseList.item(3)
        item.setText(_translate("MainWindow", "Graph 4"))
        self.GraphPageChooseList.setSortingEnabled(__sortingEnabled)
from PyQt5 import QtWebEngineWidgets
import resources_rc
